name: update my profile

on:
  # 每日触发
  schedule:
    - cron: "0 0 * * *" 
  
  # 允许手动触发
  workflow_dispatch:
  
  # 更新主仓库时启动
  # push:
  #   branches:
  #   - master
    
  

jobs:
  generate:
    permissions:
      # 给程序读写仓库的权限
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # 生成吃掉我个人贡献图的 Python
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-contribution-grid-snake.svg?color_snake=blue
            github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=blue
